client-html/src/tests/automation/import-templates/CreateImportTemplate.Epic.test.ts, client-html/src/tests/automation/import-templates/GetImportTemplate.Epic.test.ts, client-html/src/tests/automation/import-templates/GetImportTemplatesList.Epic.test.ts, client-html/src/tests/automation/import-templates/RemoveImportTemplate.Epic.test.ts, client-html/src/tests/automation/import-templates/UpdateImportTemplate.Epic.test.ts, client-html/src/tests/common/Default.Epic.ts
Added default test epic and created jest test for automation email templates (get, create, update, delete and list)
=> Jest test for Automation email templates

client-html/src/js/common/components/form/form-fields/EditInPlaceQuerySelect.tsx
fix autocomplete for the `is empty` AQL expression
=> OD-14720 AQL search for class with no room

server/src/main/groovy/ish/oncourse/server/cayenne/Contact.groovy
This preliminary work needs to be verified. We want to mirror the way product/contact relations work so that the DSL is easy to use here.
=> Improve usability of contact relationships in the DSL

client-html/src/dev/mock/api/entities/DocumentApiMock.ts, client-html/src/dev/mock/data/entities/documents.ts, client-html/src/js/common/components/list-view/components/bottom-app-bar/BottomAppBar.tsx, client-html/src/js/containers/entities/documents/components/BinCogwheel.tsx, client-html/src/tests/common/MockedEditView.Components.tsx, client-html/src/tests/entities/documents/BinCogwheel.Component.test.tsx
Added mock data of document list, added new route for delete and restore documents
=> Added jest test in Document for BinCogwheel

server/src/main/resources/imports/contactCsvImport.groovy
Updated import to allow for changes to Gender enum made some time ago.
=> Updated contact import for new gender enum

server/src/main/java/ish/oncourse/server/print/PrintService.java
Fix return object for cases when file name is not assigned
=> OD-16075 Fix report closure return value

server/src/main/groovy/ish/oncourse/server/api/service/MessageApiService.groovy, server/src/main/groovy/ish/oncourse/server/api/v1/function/MessageFunctions.groovy
=> Fix the case when source entity is different from template entity

client-html/src/js/common/components/list-view/components/side-bar/components/FilterItem.tsx, client-html/src/js/common/components/list-view/components/side-bar/components/StubFilterItem.tsx
=> OD-16884 Filter tool tips obscuring checkboxes

gradle/wrapper/gradle-wrapper.properties
…adle_6.8.2_until_we_solve_upgrade_problems_OD-17088
=> Revert_to_Gradle_6.8.2_until_we_solve_upgrade_problems_OD-17088

api-test/src/test/resources/ish/oncourse/api/test/list/entity/exportTemplate/delete.feature, api-test/src/test/resources/ish/oncourse/api/test/list/entity/exportTemplate/export/post.feature, api-test/src/test/resources/ish/oncourse/api/test/list/entity/exportTemplate/get.feature, api-test/src/test/resources/ish/oncourse/api/test/list/entity/exportTemplate/patch.feature, api-test/src/test/resources/ish/oncourse/api/test/list/entity/exportTemplate/put.feature, api-test/src/test/resources/ish/oncourse/api/test/list/entity/report/post.feature, api-test/src/test/resources/ish/oncourse/api/test/list/export/get.feature, api-test/src/test/resources/ish/oncourse/api/test/list/export/template/get.feature, api-test/src/test/resources/ish/oncourse/api/test/tag/put.feature, client-html/src/js/common/components/navigation/navigation.json, server/src/main/resources/exports/catalog.yaml, server/src/main/resources/imports/catalog.yaml, server/src/main/resources/messages/catalog.yaml, server/src/main/resources/scripts/catalog.yaml
None of the updates I made to the incorrect descriptions were added to angel 113.2835 so some of the category descriptions in the dashboard at the moment are completely wrong. The sooner this gets merged the better.
=> Improve descriptions od 17104

server/src/main/groovy/ish/oncourse/server/api/v1/service/impl/ContactInsightApiImpl.groovy
=> fix: change query to database to avoid loading of all notes … OD-17193 

server/src/main/groovy/ish/oncourse/server/cayenne/Application.groovy
=> fix: change class of TagRelation related to Application enti… OD-17237

server/src/main/groovy/ish/oncourse/server/cayenne/Note.groovy, server/src/main/resources/cayenne/AngelMap.map.xml
… save; remove not null constraint from interaction date on cayenne level
=> fix: add preinitialization of interaction date of note before… OW-3986 

server/src/main/resources/data/upgrades.yml, server/src/main/resources/database/115.upgrade.yml
…supported entityIdentifier properties before their update with cayenne
=> feat: removing of TagRelations and TagRequirements with not … OD-17129 

server/src/main/groovy/ish/oncourse/server/api/v1/function/DataCollectionFunctions.groovy
…versal data collections field types
=> feat: remove tags with tagRequirements for contacts from uni… OD-17312 

client-html/src/js/containers/automation/containers/integrations/components/forms/MYOBForm.tsx
=> fix: simplify check of values object to allow form to use it… OD-16940 

server-api/src/main/resources/def/entity/contact/insight/ContactInteraction.yaml, server-api/src/main/resources/def/entity/contact/insight/ContactOverview.yaml, server/src/main/groovy/ish/oncourse/server/api/v1/function/AuditFunctions.groovy, server/src/main/groovy/ish/oncourse/server/api/v1/service/impl/ContactInsightApiImpl.groovy, server/src/main/groovy/ish/oncourse/server/cayenne/AttachmentRelation.groovy, server/src/main/groovy/ish/oncourse/server/cayenne/ContactActivityTrait.groovy
…th local datetime to increase accuracy of activities
=> feat: replace local date into contact interactions models wi… OD-17390 

server/src/main/groovy/ish/oncourse/server/cayenne/AbstractInvoice.groovy
…amounts without tax with amounts including tax
=> feat: replace into invoices description of contact insights … OD-17393 

api-test/src/test/resources/ish/oncourse/api/test/list/entity/invoice/put.feature, server/src/main/groovy/ish/oncourse/server/integration/alchemer/AlchemerScriptClosure.groovy
=> fix: add ending for alchemer script closure code block into … OD-17448

client-html/src/js/containers/automation/containers/integrations/components/forms/XeroForm.tsx
=> fix: add name of integration to redirect url as query parame… OD-17473 

server/src/main/groovy/ish/oncourse/server/cayenne/TutorAttendance.groovy
=> feat: add startDateTime and endDateTime TutorAttendance fiel… OD-UNNUM 

api-test/src/test/resources/ish/oncourse/api/test/export/avetmiss8/get.feature, api-test/src/test/resources/ish/oncourse/api/test/export/avetmiss8/put.feature
=> feat: return checks for files format into avetmiss export ap… OD-17478 

server/src/main/groovy/ish/oncourse/server/api/v1/function/AuthenticationFunctions.groovy
…A has illegal token to avoid NPE
=> fix: add check if user without scratch codes with allowed TF… OD-17776

server/src/main/java/ish/oncourse/server/duplicate/DuplicateCourseClass.java
=> feat: add duplication of budgeted places number if class dup… OD-17805

client-html/src/js/common/components/list-view/ListView.tsx, client-html/src/js/common/components/list-view/components/bottom-app-bar/BottomAppBar.tsx, client-html/src/js/common/components/list-view/components/bottom-app-bar/components/ScriptsMenu.tsx, client-html/src/js/common/components/list-view/components/list/ReactTableList.tsx, client-html/src/js/common/epics/EpicGetScripts.ts, client-html/src/js/containers/automation/containers/scripts/components/ExecuteScriptModal.tsx, client-html/src/js/containers/automation/containers/scripts/components/cards/TriggerCardContent.tsx, client-html/src/js/containers/entities/invoices/Invoices.tsx, client-html/src/js/model/common/ListView.ts
=> Added ui and logic for running quotes and invoices scripts s… OD-17844 

server/src/main/groovy/ish/oncourse/server/export/avetmiss/functions/GetQualificationLevelOfEducation.groovy, server/src/main/groovy/ish/oncourse/server/export/avetmiss8/Avetmiss030Factory.groovy
=> fix: add support for nullable qualification level to avetmis… OD-18049 

server/src/main/groovy/ish/oncourse/server/api/service/EntityApiService.groovy
…rds instead of filter or search
=> feat: change priority in bulk delete to ids of selected reco… OD-18078 

server/src/main/groovy/ish/oncourse/server/cayenne/ClassCost.groovy, server/src/main/java/ish/budget/ClassCostUtil.java
…st has ER_TIMETABLED_HOUR type; make param of getSessionPayableHours nullable
=> feat: remove check for tutor attendance end date if class co… OD-18219 

server/src/main/groovy/ish/oncourse/server/messaging/MessageService.groovy
… recipients in "to" param if it was overridden into closure even if content was configured via email template
=> Message_spec_to_param_override OD-18246

server/src/main/resources/scripts/ish.script.abandonedCartReminder.groovy
… classes to default abandoned cart reminder
=> feat: add check if shopping cart doesn't contain products or… OD-18326 

client-html/src/js/common/components/list-view/components/bottomDrawerStyles.ts, client-html/src/js/common/components/list-view/components/share/ShareContainer.tsx, client-html/src/js/containers/automation/containers/export-templates/actions/index.ts, client-html/src/js/containers/automation/containers/export-templates/services/ExportTemplatesService.ts, client-html/src/js/containers/automation/containers/pdf-reports/actions/index.ts, client-html/src/js/containers/automation/containers/pdf-reports/services/PdfService.ts, server-api/src/main/resources/path/list/entity/exportTemplate/preview/api.yaml, server-api/src/main/resources/path/list/entity/report/preview/api.yaml, server/src/main/groovy/ish/oncourse/server/api/v1/service/impl/ExportTemplateApiImpl.groovy, server/src/main/groovy/ish/oncourse/server/api/v1/service/impl/PdfTemplateApiImpl.groovy, server/src/main/java/ish/oncourse/server/api/service/AutomationApiService.java, server/src/main/java/ish/oncourse/server/api/service/ExportTemplateApiService.java, server/src/main/java/ish/oncourse/server/api/service/ReportApiService.java
=> feat: add compression for export templates api request for s… OD-18365 

server/src/main/groovy/ish/oncourse/server/cayenne/AbstractInvoiceLine.groovy, server/src/main/java/ish/oncourse/aql/model/EntityFactory.java, server/src/main/java/ish/oncourse/aql/model/attribute/AccountAbstractInvoiceLines.java, server/src/main/java/ish/oncourse/aql/model/attribute/CourseClassAbstractInvoiceLines.java, server/src/main/java/ish/oncourse/aql/model/attribute/EnrolmentAbstractInvoiceLines.java, server/src/main/java/ish/oncourse/aql/model/attribute/TaxAbstractInvoiceLines.java, server/src/main/resources/cayenne/AngelMap.map.xml
… invoice lines; add their logic to synthetic aql attributes
=> fix: return renamed related from AbstractInvoice to abstract… OD-18372 

api-test/src/test/resources/ish/oncourse/api/test/list/entity/note/get.feature, api-test/src/test/resources/ish/oncourse/api/test/list/entity/note/post.feature, api-test/src/test/resources/ish/oncourse/api/test/list/entity/note/put.feature, client-html/src/js/common/components/form/notes/components/NoteItem.tsx, server-api/src/main/resources/def/entity/Note.yaml, server/src/main/groovy/ish/oncourse/server/api/v1/function/NoteFunctions.groovy, server/src/main/groovy/ish/oncourse/server/cayenne/Note.groovy, server/src/main/resources/cayenne/AngelMap.map.xml, server/src/main/resources/database/131.upgrade.yml, types/src/main/java/ish/common/types/EntityMapping.java
=> feat: replication of notes from portal and readonly paramete… OD-18545 

server/src/main/java/ish/oncourse/server/print/PrintService.java
=> fix: add check if report for key code not found, but cayenne … OW-4511

server-api/src/main/groovy/ish/oncourse/server/api/traits/DataTypeDTOTrait.groovy
=> fix: add ability to create options in automations with number… OW-4571 

server/src/main/groovy/ish/oncourse/server/scripting/GroovyScriptService.groovy, server/src/main/java/ish/oncourse/server/license/LicenseService.java, server/src/main/resources/messages/catalog.yaml, server/src/main/resources/messages/ish.email.studentPortalInvitation.html, server/src/main/resources/messages/ish.email.studentPortalInvitation.txt, server/src/main/resources/scripts/catalog.yaml, server/src/main/resources/scripts/ish.script.sendPortalPasswordNotification.groovy
…, using current services endpoint
=> feat: script to check if contacts don't have portal password… OD-18959 
